---
markdown: redcarpet
redcarpet:
  extensions:
  - tables
  - with_toc_data
pygments: true
baseurl: "/python-mcider"
encoding: UTF-8
exclude:
- README.md
- vendor
- tmp
name: mCider
copyright: 2014, ogom
theme: cerulean
